### ISSUE TITLE
Fix wrong config in example

### ISSUE THREAD

**Issue by Touutae-lab** [apache/incubator-pekko-grpc-quickstart-scala.g8#6]
[GreeterServer.scala#L40](https://github.com/apache/incubator-pekko-grpc-quickstart-scala.g8/blob/main/src/main/g8/src/main/scala/com/example/helloworld/GreeterServer.scala#L40)

from pekko.http.server.enable-http2 = on to pekko.http.server.preview.enable-http2 = on 

as https://pekko.apache.org/docs/pekko-http/1.0/troubleshooting/unsupported-http-method-pri.html say

**Comment by Touutae-lab** [comment]
current config cause error in example
![image](https://github.com/apache/incubator-pekko-grpc-quickstart-scala.g8/assets/58826535/90eb3293-72e6-4557-8875-e90106495444)

**Comment by dward2nd** [comment]
Such the line can be found on [GreeterSpec.scala#L28](https://github.com/apache/incubator-pekko-grpc-quickstart-scala.g8/blob/06472513cfc4afbdb5f327c1d857f9a51107bb7b/src/main/g8/src/test/scala/com/example/helloworld/GreeterSpec.scala#L28) as well.

**Comment by pjfanning** [comment]
thanks - I've raised https://github.com/apache/incubator-pekko-grpc-quickstart-scala.g8/pull/7
